In [8]:
# Question 1
# A program that will find all numbers which are divisible by 7 but are not a multiple of 5,
# between 2000 and 3200 (both included). The numbers obtained should be printed in a list.

#To create an empty List
nl=[]
for x in range(2000, 3200):
    if (x%7==0) & (x%5!=0):
        nl.append(x)        
print(nl)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [10]:
# Question 2
# Python program to find the factorial of a number provided by the user
# Change manually the value for a different result
# To take input from the user
num = int(input("Enter a number: "))
fact = 1

# check if the number is negative, zero, or positive
if num < 0:
     print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
     print("The factorial of 0 is 1")
else:
    for i in range(1,num + 1):
        fact = fact*i
print("The factorial of",num,"is",fact)

Enter a number: 4
The factorial of 4 is 24


In [11]:
# Question 3
# Write a program to generate a dictionary for an integer number n that contains (i, i*i) such that
# is an integral number between 1 and n. 

# n=8
n= int(input("Type a number: "))
d={}
for i in range(1,n+1):
    d[i]=i*i
print(d)

Type a number: 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [20]:
# Question 4
# Given a non-empty string and an int n, return a new string where the char at index n has been removed

def missing_char(str, n):
# The str not including n
    return str[:n] + str[n+1:]

word=input("Type a word: ")
n=int(input("Type a number: "))
missing_char(word, n)

Type a word: BILAL
Type a number: 2


'BIAL'

In [21]:
# Question 5
# Write a NumPy program to convert a NumPy array into a Python list structure.
# Expected Output: 
# Original array elements: [[0 1] [2 3] [4 5]] 
# Array to list: [[0, 1], [2, 3], [4, 5]] 
  
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:\n", x)
print("Array to list:\n",x.tolist())

Original array elements:
 [[0 1]
 [2 3]
 [4 5]]
Array to list:
 [[0, 1], [2, 3], [4, 5]]


In [22]:
# Question 6
# Write a NumPy program to compute the covariance matrix of two given arrays. 
# Original array1: [0 1 2] and Original array2: [2 1 0] 
# Covariance matrix of the said arrays: [[ 1. -1.] [-1. 1.]]

import numpy as np
Tab1 = np.array([0, 1, 2])
Tab2 = np.array([2, 1, 0])
print("Original array1:\n", Tab1)
print("Original array1:\n", Tab2)
print("Covariance matrix of the said arrays:\n",np.cov(Tab1, Tab2))

Original array1:
 [0 1 2]
Original array1:
 [2 1 0]
Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]
